### ISSUE TITLE
Clang / GFortran breaks OpenMP

### ISSUE THREAD

**Issue by paspro** [code-saturne/code_saturne#107]
If the user chooses the Clang compiler for C/C++ and the GFortran compiler for the Fortran code then the configuration script fails to enable the OpenMP option for the Fortran compiler and it enables it for the Clang compiler only.

**Comment by YvanFournier** [comment]
This is a feature, not a bug... To my knowlege, clang and gfortran use different OpenMP libraries, and mixing the 2 may be risky.

Since we are progressively migrating to C and there is very little OpenMP code left in the Fortran part, this should not be a significant performance issue (and we have a lot of work on the C side to increase the ration of OpenMP et serial sections if we are to get good performance at all).
