### ISSUE TITLE
Cannot build master on certain systems: template function cs_datatype_from_type() cannot instantiate

### ISSUE THREAD

**Issue by paspro** [code-saturne/code_saturne#138]
On certain systems, such as macOS, the current master cannot be built because of the failure to instantiate template function cs_datatype_from_type() in file base/cs_defs.h where we see the specialisation:

```
template <>
constexpr inline cs_datatype_t
cs_datatype_from_type<uint64_t>()
{
  return CS_UINT64;
}

```

This is because uint64_t is defined as "unsigned long" in typical Linux systems but on other systems it is  defined as "unsigned long long" and so some integers in code_saturne defined as "unsigned long" which are still 8 byte data elements find no template specialisation function for cs_datatype_from_type(). The fix is easy: add the following template speciialisation in cs_defs.h:

```
template <>
constexpr inline cs_datatype_t
cs_datatype_from_type<unsigned long>()
{
  return CS_UINT64;
}

```

**Comment by YvanFournier** [comment]
Hello Panos,

Rather than defining additional templates, I changed the `cs_gnum_t` typedef to `uint64_t` when the code is configured to use long gnum types (which has been the default for a while).

Looking at the code paths where cs_datatype_from_type is called, I thing this should solve your issue, and this makes the logic simpler in several places. Depending on your feedback on macOS, I 'll add the additional template if it is still needed.

**Comment by paspro** [comment]
Ok, this modification fixed the problem with no need to add the template specialisation.
