### ISSUE TITLE
Total number of internal faces wrong after joining ?

### ISSUE THREAD

**Issue by rbresson** [code-saturne/code_saturne#14]
Hi,

I've got a mesh with a periodicity in the x direction.
I noticed in the listing that the total number (i.e. over the whole mesh) of internal faces printed after joining periodic faces seems wrong, since the boundary faces which have been joined are then counted twice. 

This is not coherent with how the number of upwind faces are counted, for example.

Indeed, with the upwind scheme activated for any variable I can read in the listing that I get 

m upwind faces over a total of n internal faces

where m<n !!!

Raphael

**Comment by YvanFournier** [comment]
Hello,

Periodic faces should be counted on each end. In your case, does it seem the total number of faces is wrong, or upwind faces are counted an extra time ?

**Comment by YvanFournier** [comment]
Actually it is probably the other way around: a filter to avoid duplicate parallel counts probably reduces the count here... 

Improving that filter would be quite costly performance-wise, so we may leave things as is for the moment.

**Comment by YvanFournier** [comment]
Also please post in English. It should seem obvious.

**Comment by foufara4853** [comment]
I switched my initial comment to english...

**Comment by YvanFournier** [comment]
A solution would be to separately count "numerical" faces (where 2 periodic faces would be counted as 1, as they are equivalent) and "geometrical" faces (where 2 periodic faces are separate, as they have different centers and possibly normals).

This way, the current count (avoiding duplicate counts on faces adjacent to ghost cells) could simply be compared to the total numerical faces instead of the total faces (i.e. n_g_i_faces - n_g_periodic_face_couples instead of n_g_i_faces).
