### ISSUE TITLE
Problem with CGNS 3.4.1 and Code_saturne 6.0.2

### ISSUE THREAD

**Issue by thierry-FreeBSD** [code-saturne/code_saturne#58]
With cgnslib 3.4.1, there is an error:
in function `ecs_pre_cgns__lit_maillage':
ecs_pre_cgns.c:(.text+0x2db6): undefined reference to `cg_poly_elements_read'

I fixed it by replacing 3400 by 3402 in preprocessor/pre-post/ecs_pre_cgns.c and src/fvm/fvm_to_cgns.c

No pull request because I do not think that this is the best solution, but this is a work-around.

**Comment by YvanFournier** [comment]
CGNS broke upwards compatibility with 3.4.0, and to "fix" this, they decided the smart thing to do was to break it again (Feb 2020): [http://cgns.github.io/news.html](url). Not sure what they were thinking, but this makes this a pain for those who keep up to date rather than those who wake up 3 years later...

So version 3.4.0 should behave like 4.0.0, and 3.4.1 like 3.3.x...
I have not tested yet but 4.0 should be ok without test modifications. In the code, I will need to do finer-grained tests...

**Comment by thierry-FreeBSD** [comment]
No more problem with cgnslib-4.1.1.
