### ISSUE TITLE
7.3 does not build on macOS

### ISSUE THREAD

**Issue by paspro** [code-saturne/code_saturne#99]
After the change to the makefiles and the introduction of the $ORIGIN parameter for relocatable builds, code_saturne can no longer compile under macOS because the native linker does not support this parameter, even when using the GNU toolchain since the native linker must always be used. The equivalent parameter for the macOS linker is called @loader_path.

**Comment by paspro** [comment]
A solution for this problem is the following:

1. In file configure.ac set `LDRPATH="-Wl,-rpath,"` because otherwise on macOS this is an empty string.
2. In files `preprocessor/appli/Makefile.am` and `src/apps/Makefile.am` replace the existing term with the following:

```
# Relocatable installation

if HAVE_RELOCATABLE
  ORIGINRUNPATH = $(LDRPATH)'\@loader_path/../../lib'
  PLUGINRUNPATH_R = $(LDRPATH)'\@loader_path/../../lib/'$(PACKAGE)
else
  PLUGINRUNPATH_N = $(LDRPATH)$(pkglibdir)
endif

```

**Comment by paspro** [comment]
On another note, for macOS in file src/base/cs_system_info.c the lines:

```
#if defined(__linux__)
#include <stdio.h>
#endif

```
have to be modified so that this include statement is active

`#include <stdio.h>`

because stdio.h is needed for proper compilation like in Linux.

**Comment by YvanFournier** [comment]
Hello,

Regarding `stdio.h`, I'll change it so that it is always included.

For `LDRPATH`, this is built from an initial `ldflags_rpath` variable, which should be set is in `config/cs_auto_flags.sh` to be more consistent (see "default linker flags near the end). Could you confirm that "host_os" appears as "darwin" in for Mac OS so I can add the test ? There are other tests with "darwin*" in the same file.

I'll let you either propose a patch, or I can write one in the newt few days and let you test it, whichever you prefer.

**Comment by paspro** [comment]
Yes, it is called "darwin".

**Comment by paspro** [comment]
These modifications fixed the problems and code_saturne now builds correctly on macOS.
